export const SENSORS = [
  {
    id: 'temperature',
    key: 'temperature',
    name: 'Temperature',
    unit: '°C',
    min: 0.0,
    max: 50.0,
    defaultVal: 25.0,
    step: 0.1,
    signal: 'DAC',
    espPin: 'GPIO 25',
    arduinoPin: 'A0',
    color: '#ff4d4f',
    glowColor: 'rgba(255, 77, 79, 0.4)',
    hex: 0xff4d4f,
    description: 'Analog thermal simulator driving Arduino A0 (0–3.3V DAC)'
  },
  {
    id: 'humidity',
    key: 'humidity',
    name: 'Relative Humidity',
    unit: '%',
    min: 0.0,
    max: 100.0,
    defaultVal: 50.0,
    step: 0.5,
    signal: 'DAC',
    espPin: 'GPIO 26',
    arduinoPin: 'A1',
    color: '#13c2c2',
    glowColor: 'rgba(19, 194, 194, 0.4)',
    hex: 0x13c2c2,
    description: 'Analog moisture simulator driving Arduino A1 (0–3.3V DAC)'
  },
  {
    id: 'gas',
    key: 'gas',
    name: 'Gas Concentration',
    unit: 'ppm',
    min: 0.0,
    max: 1000.0,
    defaultVal: 300.0,
    step: 5.0,
    signal: 'PWM',
    espPin: 'GPIO 18',
    arduinoPin: 'D4',
    color: '#faad14',
    glowColor: 'rgba(250, 173, 20, 0.4)',
    hex: 0xfaad14,
    description: '500 Hz PWM pulse train driving Arduino digital pin D4'
  },
  {
    id: 'light',
    key: 'light',
    name: 'Ambient Light',
    unit: 'lux',
    min: 0.0,
    max: 1000.0,
    defaultVal: 500.0,
    step: 5.0,
    signal: 'PWM',
    espPin: 'GPIO 19',
    arduinoPin: 'D5',
    color: '#52c41a',
    glowColor: 'rgba(82, 196, 26, 0.4)',
    hex: 0x52c41a,
    description: '500 Hz PWM pulse train driving Arduino digital pin D5'
  },
  {
    id: 'soil',
    key: 'soil',
    name: 'Soil Moisture',
    unit: '%',
    min: 0.0,
    max: 100.0,
    defaultVal: 50.0,
    step: 0.5,
    signal: 'PWM',
    espPin: 'GPIO 21',
    arduinoPin: 'D6',
    color: '#722ed1',
    glowColor: 'rgba(114, 46, 209, 0.4)',
    hex: 0x722ed1,
    description: '500 Hz PWM pulse train driving Arduino digital pin D6'
  }
];

export const GROUND_WIRE = {
  id: 'gnd',
  name: 'Common Ground',
  espPin: 'GND',
  arduinoPin: 'GND',
  color: '#8c8c8c',
  hex: 0x595959,
  description: 'Common electrical voltage reference (strictly required)'
};
